from pathlib import Path
from typing import Protocol

from app.core.config import get_settings
from app.modules.auth import security


class FileStorage(Protocol):
    async def save(self, *, key: str, content: bytes, content_type: str) -> None: ...
    async def read(self, *, key: str) -> bytes: ...
    async def delete(self, *, key: str) -> None: ...


class LocalFileStorage:
    """Filesystem-backed FileStorage — fine for a single-instance deployment, not for anything
    horizontally scaled. Swap for an S3-backed implementation before that's a requirement; nothing
    outside this module needs to change, callers only depend on the FileStorage protocol.

    Keys are always generated by the service layer (never taken from client input), so this class
    doesn't need to defend against path traversal in the key itself — but it does refuse to
    resolve outside the storage root as a second line of defense.
    """

    def __init__(self, root: str | None = None) -> None:
        self._root = Path(root or get_settings().storage_dir)
        self._root.mkdir(parents=True, exist_ok=True)

    def _resolve(self, key: str) -> Path:
        path = (self._root / key).resolve()
        if self._root.resolve() not in path.parents and path != self._root.resolve():
            raise ValueError(f"Storage key resolves outside the storage root: {key!r}")
        return path

    async def save(self, *, key: str, content: bytes, content_type: str) -> None:
        path = self._resolve(key)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(content)

    async def read(self, *, key: str) -> bytes:
        return self._resolve(key).read_bytes()

    async def delete(self, *, key: str) -> None:
        path = self._resolve(key)
        path.unlink(missing_ok=True)


class EncryptingFileStorage:
    """Wraps another FileStorage and transparently encrypts content at rest — save() encrypts
    before delegating, read() decrypts after delegating, delete() passes through unchanged
    (nothing to encrypt). Uses the same Fernet key-provider seam as every other encrypted field
    in this app (app.modules.auth.security.encrypt_bytes/decrypt_bytes, backed by
    app.core.key_provider) rather than a per-instance key override — tests that need a
    different key use the existing global set_key_provider() hook, same as everywhere else
    encrypted fields are tested.

    Composition, not inheritance: this lets any FileStorage implementation (LocalFileStorage
    today, an eventual S3-backed one) gain encryption-at-rest for free without touching that
    implementation itself."""

    def __init__(self, inner: FileStorage) -> None:
        self._inner = inner

    async def save(self, *, key: str, content: bytes, content_type: str) -> None:
        await self._inner.save(
            key=key, content=security.encrypt_bytes(content), content_type=content_type
        )

    async def read(self, *, key: str) -> bytes:
        encrypted = await self._inner.read(key=key)
        return security.decrypt_bytes(encrypted)

    async def delete(self, *, key: str) -> None:
        await self._inner.delete(key=key)
