from pathlib import Path
from typing import Protocol

from app.core.config import get_settings


class FileStorage(Protocol):
    async def save(self, *, key: str, content: bytes, content_type: str) -> None: ...
    async def read(self, *, key: str) -> bytes: ...
    async def delete(self, *, key: str) -> None: ...


class LocalFileStorage:
    """Filesystem-backed FileStorage — fine for a single-instance deployment, not for anything
    horizontally scaled. Swap for an S3-backed implementation before that's a requirement; nothing
    outside this module needs to change, callers only depend on the FileStorage protocol.

    Keys are always generated by the service layer (never taken from client input), so this class
    doesn't need to defend against path traversal in the key itself — but it does refuse to
    resolve outside the storage root as a second line of defense.
    """

    def __init__(self, root: str | None = None) -> None:
        self._root = Path(root or get_settings().storage_dir)
        self._root.mkdir(parents=True, exist_ok=True)

    def _resolve(self, key: str) -> Path:
        path = (self._root / key).resolve()
        if self._root.resolve() not in path.parents and path != self._root.resolve():
            raise ValueError(f"Storage key resolves outside the storage root: {key!r}")
        return path

    async def save(self, *, key: str, content: bytes, content_type: str) -> None:
        path = self._resolve(key)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(content)

    async def read(self, *, key: str) -> bytes:
        return self._resolve(key).read_bytes()

    async def delete(self, *, key: str) -> None:
        path = self._resolve(key)
        path.unlink(missing_ok=True)
